Repository donkim1212/nbc_ch2_tmdb, pull requests merged in 2024-05, with the labels that each got.

#22 [FEATURE][리뷰 페이지] 리뷰 페이지 내용 FEATURE
  README.md
  index.html
  js/card.js
  js/fetch-movies-db.js
  js/index.js
  js/review.js
  js/search-movie.js
Labels: FEATURE

#21 sortcard
  css/mystyle.css
  index.html
  js/index.js
  js/search-filter.js
Labels: FEATURE

#19 Feat/movie info loader
  css/info-style.css
  index.html
  js/card.js
  js/index.js
  js/movie-info-loader.js
Labels: FEATURE

#20 [FEATURE][TMDB API] 필요한 API를 추가하기
  .github/pull_request_template.md
  .gitignore
  js/fetch-movies-db.js
  js/search-movie.js
Labels: FEATURE

#27 [Update]Review 2
  js/review.js
Labels: UPDATE

#28 Update/movie info loader
  css/info-style.css
  js/index.js
  js/movie-info-loader.js
Labels: UPDATE, STYLE

#30 Combine features
  css/info-style.css
  css/review-style.css
  index.html
  js/card.js
  js/index.js
  js/movie-info-loader.js
  js/review.js
Labels: UPDATE, STYLE, BugFix

#37 Update/style
  css/info-review-899.css
  css/info-style.css
  css/mystyle.css
  css/review-style.css
  index.html
  js/review.js
  js/search-filter.js
Labels: STYLE

#39 Style: add css transition to card-info and search (vice-versa)
  css/mystyle.css
  css/review-style.css
Labels: STYLE

#38 Project 3 배포
  .github/ISSUE_TEMPLATE/issue--bugfix.md
  .github/ISSUE_TEMPLATE/issue--docs.md
  .github/ISSUE_TEMPLATE/issue--feature.md
  .github/ISSUE_TEMPLATE/issue--refactor.md
  .github/pull_request_template.md
  .gitignore
  README.md
  css/info-review-899.css
  css/info-style.css
  css/mystyle.css
  css/review-style.css
  index.html
  js/card.js
  js/fetch-movies-db.js
  js/index.js
  js/movie-info-loader.js
  js/review.js
  js/search-filter.js
  js/search-movie.js
  js/simple-toggler.js
Labels: DEPLOY
